# Generated by Django 5.0.2 on 2024-03-20 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catrgories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('discount', models.IntegerField()),
                ('catrgory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.catrgories')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.companyname')),
            ],
        ),
    ]
